### PR TITLE
external sources use the same protocol https/http

### PR DESCRIPTION
**Pull request by vokimon**

### CODE REVIEW

**Comment by vokimon** [comment]
Almost working version using https try it at:
https://rawgit.com/Som-Energia/powered-by-somenergia/afa380ae88eaa5b0288a0ae8beae13a36121178d/index.html

Remaining Issue: zoom in or out and you lose all the tiles (they seem to be actually downloaded but not shown)

**Comment by ghost** [comment]
@vokimon  Molt bona feina.

**Comment by ghost** [comment]
@vokimon no puc fer un 'merge'. Potser tu puguis.

**Comment by ghost** [comment]
@vokimon Com puc després dur els canvis teus al meu repositori?

**Comment by ghost** [comment]
@vokimon Venga!. Puc ser l'admin.

**Comment by ghost** [comment]
Fet https://github.com/somenxavier/powered-by-somenergia/pull/1

**Pull request merged**
